import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageState extends ChangeNotifier {
  String _locale = 'th';
  String get locale => _locale;

  LanguageState() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _locale = prefs.getString('language') ?? 'th';
    notifyListeners();
  }

  Future<void> setLanguage(String langCode) async {
    _locale = langCode;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', langCode);
    notifyListeners();
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'th': {
      'app_title': 'บัญชีรายรับรายจ่าย',
      'balance': 'ยอดเงินคงเหลือ',
      'income': 'รายรับ',
      'expense': 'รายจ่าย',
      'history': 'ประวัติ',
      'summary': 'สรุป',
      'settings': 'ตั้งค่า',
      'hello': 'สวัสดี',
      'recent': 'รายการล่าสุด',
      'baht': 'บาท',
      'language': 'ภาษา',
      'dark_mode': 'โหมดมืด',
      'logout': 'ออกจากระบบ',
      'admin_panel': 'แผงควบคุมแอดมิน',
      'users': 'ผู้ใช้',
      'stats': 'สถิติ',
      'warning_negative': 'ระวัง! ยอดเงินของคุณติดลบ กรุณาวางแผนการใช้จ่าย',
      'add_income': 'เพิ่มเงิน',
      'add_expense': 'ใช้เงิน',
      'home': 'หน้าหลัก',
      'login': 'เข้าสู่ระบบ',
      'register': 'สมัครสมาชิก',
      'username': 'ชื่อผู้ใช้',
      'password': 'รหัสผ่าน',
      'confirm_password': 'ยืนยันรหัสผ่าน',
      'no_data': 'ไม่มีข้อมูล',
      'loading': 'กำลังโหลด...',
      'error_network': 'ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้',
      'error_fields': 'กรุณากรอกข้อมูลให้ครบถ้วน',
      'error_pass_match': 'รหัสผ่านไม่ตรงกัน',
      'error_pass_short': 'รหัสผ่านต้องมีอย่างน้อย 4 ตัวอักษร',
      'error_pass_same_user': 'รหัสผ่านห้ามซ้ำกับชื่อผู้ใช้',
      'error_lang_limit': 'อนุญาตเฉพาะภาษาอังกฤษและตัวเลขเท่านั้น',
      'today': 'วันนี้',
      'week': 'สัปดาห์',
      'month': 'เดือน',
      'all': 'ทั้งหมด',
      'total_system': 'สถิติภาพรวมทั้งระบบ',
      'user_summary': 'สรุปรายบุคคล',
      'refresh': 'รีเฟรช',
      'welcome': 'ยินดีต้อนรับ',
      'login_subtitle': 'เข้าสู่ระบบบัญชีรายรับรายจ่าย',
      'register_subtitle': 'กรอกข้อมูลเพื่อสร้างบัญชีผู้ใช้',
      'fields_required': 'กรุณากรอกข้อมูลให้ครบถ้วน',
      'invalid_credentials': 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
      'timeout_error': 'เซิร์ฟเวอร์ตอบสนองช้า กรุณาลองใหม่',
      'connection_error': 'ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้',
      'note': 'หมายเหตุ',
      'delete_item': 'ลบ',
      'confirm_delete': 'ยืนยันการลบ',
      'delete_question': 'คุณแน่ใจหรือไม่ที่จะลบรายการนี้?',
      'cancel': 'ยกเลิก',
      'save': 'บันทึก',
      'close': 'ปิด',
      'edit': 'แก้ไข',
      'items': 'รายการ',
      'yesterday': 'เมื่อวาน',
      'desc_label': 'รายละเอียด',
      'desc_hint': 'เช่น ค่าอาหารกลางวัน',
      'amount_label': 'จำนวนเงิน',
      'note_label': 'หมายเหตุ (อธิบายเพิ่มเติม)',
      'note_hint': 'เช่น ไม่ใส่พริก, เผ็ดน้อย',
      'category': 'หมวดหมู่',
      'salary': 'เงินเดือน',
      'freelance': 'ฟรีแลนซ์',
      'bonus': 'โบนัส',
      'investment': 'ลงทุน',
      'food': 'อาหาร',
      'travel': 'การเดินทาง',
      'shopping': 'ช้อปปิ้ง',
      'bill': 'บิล/ค่าน้ำไฟ',
      'entertainment': 'บันเทิง',
      'health': 'สุขภาพ',
      'other': 'อื่นๆ',
      'username_label': 'ชื่อผู้ใช้',
      'username_hint': 'กรอกชื่อผู้ใช้',
      'password_label': 'รหัสผ่าน',
      'password_hint': 'กรอกรหัสผ่าน',
      'confirm_password_label': 'ยืนยันรหัสผ่าน',
      'confirm_password_hint': 'กรอกรหัสผ่านอีกครั้ง',
      'login_btn': 'เข้าสู่ระบบ',
      'register_btn': 'สมัครสมาชิก',
      'no_account': 'ยังไม่มีบัญชี?',
      'has_account': 'มีบัญชีอยู่แล้ว?',
      'register_success': 'สมัครสมาชิกสำเร็จ กรุณาเข้าสู่ระบบ',
      'register_failed': 'เกิดข้อผิดพลาดในการสมัครสมาชิก',
      'search_hint': 'ค้นหารายการ...',
      'monthly_budget': 'งบประมาณรายเดือน',
      'over_budget': 'เกินงบประมาณ!',
      'set_budget': 'ตั้งค่ารายจ่ายที่ตั้งเป้าไว้',
      'budget_hint': 'ป้อนตัวเลขงบประมาณ',
      'expense_by_category': 'รายจ่ายแยกตามหมวดหมู่',
    },
    'en': {
      'app_title': 'Expense Tracker',
      'balance': 'Total Balance',
      'income': 'Income',
      'expense': 'Expense',
      'history': 'History',
      'summary': 'Summary',
      'settings': 'Settings',
      'hello': 'Hello',
      'recent': 'Recent Transactions',
      'baht': 'THB',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'logout': 'Logout',
      'admin_panel': 'Admin Panel',
      'users': 'Users',
      'stats': 'Stats',
      'warning_negative': 'Warning! Your balance is negative. Please plan your spending.',
      'add_income': 'Add Income',
      'add_expense': 'Add Expense',
      'home': 'Home',
      'login': 'Login',
      'register': 'Register',
      'username': 'Username',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'no_data': 'No Data',
      'loading': 'Loading...',
      'error_network': 'Server Connection Error',
      'error_fields': 'Please fill all fields',
      'error_pass_match': 'Passwords do not match',
      'error_pass_short': 'Password must be at least 4 characters',
      'error_pass_same_user': 'Password cannot be the same as username',
      'error_lang_limit': 'Only English and numbers allowed',
      'today': 'Today',
      'week': 'Week',
      'month': 'Month',
      'all': 'All',
      'total_system': 'Total System Stats',
      'user_summary': 'User Summary',
      'refresh': 'Refresh',
      'welcome': 'Welcome Back',
      'login_subtitle': 'Login to your expense account',
      'register_subtitle': 'Enter details to create an account',
      'fields_required': 'Please fill all fields',
      'invalid_credentials': 'Invalid username or password',
      'timeout_error': 'Server timeout, please try again',
      'connection_error': 'Could not connect to server',
      'note': 'Note',
      'delete_item': 'Delete',
      'confirm_delete': 'Confirm Delete',
      'delete_question': 'Are you sure you want to delete this?',
      'cancel': 'Cancel',
      'save': 'Save',
      'close': 'Close',
      'edit': 'Edit',
      'items': 'items',
      'yesterday': 'Yesterday',
      'desc_label': 'Description',
      'desc_hint': 'e.g. Lunch',
      'amount_label': 'Amount',
      'note_label': 'Note (Optional)',
      'note_hint': 'e.g. No spicy, less sugar',
      'category': 'Category',
      'salary': 'Salary',
      'freelance': 'Freelance',
      'bonus': 'Bonus',
      'investment': 'Investment',
      'food': 'Food',
      'travel': 'Travel',
      'shopping': 'Shopping',
      'bill': 'Bills/Utilities',
      'entertainment': 'Entertainment',
      'health': 'Health',
      'other': 'Other',
      'username_label': 'Username',
      'username_hint': 'Enter your username',
      'password_label': 'Password',
      'password_hint': 'Enter your password',
      'confirm_password_label': 'Confirm Password',
      'confirm_password_hint': 'Re-enter your password',
      'login_btn': 'Login',
      'register_btn': 'Register',
      'no_account': "Don't have an account?",
      'has_account': 'Already have an account?',
      'register_success': 'Registration successful! Please login.',
      'register_failed': 'Registration failed. Please try again.',
      'search_hint': 'Search transactions...',
      'monthly_budget': 'Monthly Budget',
      'over_budget': 'Over Budget!',
      'set_budget': 'Set Monthly Budget',
      'budget_hint': 'Enter budget amount',
      'expense_by_category': 'Expense by Category',
    },
    'zh': {
      'app_title': '记账本',
      'balance': '总余额',
      'income': '收入',
      'expense': '支出',
      'history': '历史',
      'summary': '总结',
      'settings': '设置',
      'hello': '你好',
      'recent': '最近交易',
      'baht': '泰铢',
      'language': '语言',
      'dark_mode': '深色模式',
      'logout': '登出',
      'admin_panel': '管理面板',
      'users': '用户',
      'stats': '统计',
      'warning_negative': '警告！您的余额为负。请计划您的开支。',
      'add_income': '增加收入',
      'add_expense': '增加支出',
      'home': '首页',
      'login': '登录',
      'register': '注册',
      'username': '用户名',
      'password': '密码',
      'confirm_password': '确认密码',
      'no_data': '没有数据',
      'loading': '加载中...',
      'error_network': '服务器连接错误',
      'error_fields': '请填写所有字段',
      'error_pass_match': '密码不匹配',
      'error_pass_short': '密码长度至少为 4 个字符',
      'error_pass_same_user': '密码不能与用户名相同',
      'error_lang_limit': '仅允许英文字母和数字',
      'today': '今天',
      'week': '本周',
      'month': '本月',
      'all': '全部',
      'total_system': '系统总体统计',
      'user_summary': '用户摘要',
      'refresh': '刷新',
      'welcome': '欢迎回来',
      'login_subtitle': '登录您的费用账户',
      'register_subtitle': '输入详细信息以创建帐户',
      'fields_required': '请填写所有字段',
      'invalid_credentials': '用户名或密码无效',
      'timeout_error': '服务器超时，请重试',
      'connection_error': '无法连接到服务器',
      'note': '备注',
      'delete_item': '删除',
      'confirm_delete': '确认删除',
      'delete_question': '你确定要删除这个吗？',
      'cancel': '取消',
      'save': '保存',
      'close': '关闭',
      'edit': '编辑',
      'items': '项目',
      'yesterday': '昨天',
      'desc_label': '描述',
      'desc_hint': '例如：午餐',
      'amount_label': '金额',
      'note_label': '备注（可选）',
      'note_hint': '例如：不辣，少糖',
      'category': '类别',
      'salary': '薪水',
      'freelance': '自由职业',
      'bonus': '奖金',
      'investment': '投资',
      'food': '食物',
      'travel': '旅游',
      'shopping': '购物',
      'bill': '账单/公用事业',
      'entertainment': '娱乐',
      'health': '健康',
      'other': '其他',
      'username_label': '用户名',
      'username_hint': '输入用户名',
      'password_label': '密码',
      'password_hint': '输入密码',
      'confirm_password_label': '确认密码',
      'confirm_password_hint': '再次输入密码',
      'login_btn': '登录',
      'register_btn': '注册',
      'no_account': '还没有账号？',
      'has_account': '已有账号？',
      'register_success': '注册成功！请登录。',
      'register_failed': '注册失败。请重试。',
      'search_hint': '搜索交易...',
      'monthly_budget': '每月预算',
      'over_budget': '超出预算！',
      'set_budget': '设置每月预算',
      'budget_hint': '输入预算金额',
      'expense_by_category': '按类别支出',
    },
  };

  String t(String key) {
    return _localizedValues[_locale]?[key] ?? key;
  }
}
